server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-169012.okta.com/oauth2/default
    client-id: 0oa1e3ohrtw6ZjPnG357
    client-secret: z_JcWmkQyWENnrOyttTWMWLEIKYHrpgPNYKbs_NG
spring:
  thymeleaf:
    cache: false
